### ISSUE TITLE
at interpolateFnWatchAction Problem in IE11

### ISSUE THREAD

**Issue by khackskjs** [irontec/angular-bootstrap-simple-chat#23]
Hello.
I'm testing this module to use in IE 11 (or 10)
when I open "http://localhost:3000/examples" in IE, 

Invalid Argument Error
at interpolateFnWatchAction (http://localhost:3000/bower_components/angular/angular.js:8838:17)
at interpolateFnWatcher (http://localhost:3000/bower_components/angular/angular.js:11327:17)

do you have solution?
thanks in advance

**Comment by khackskjs** [comment]
I solved this problem modifying library "angular-simple-chat.js" follow by [http://blog.novanet.no/angularjs-internet-explorer-textarea-and-placeholder/]
