### ISSUE TITLE
Scroll $ is not defined

### ISSUE THREAD

**Issue by Nandez89** [irontec/angular-bootstrap-simple-chat#27]
When I try to do a bower install it says that "angularjs-scroll-glue": "~0.0.1" so i use the recomended 2.2.0 instead. However upon deploy I get a few errors related to the scroll.

`angular.js:14199 TypeError: Cannot read property 'scrollTop' of undefined `

```
angular.js:14199 ReferenceError: $ is not defined
    at Object.link (http://localhost:8000/bower_components/angular-bootstrap-simple-chat/src/scripts/index.js:44:4)
    at http://localhost:8000/bower_components/angular/angular.js:1259:18
    at http://localhost:8000/bower_components/angular/angular.js:10146:44
    at invokeLinkFn (http://localhost:8000/bower_components/angular/angular.js:10152:9)
    at nodeLinkFn (http://localhost:8000/bower_components/angular/angular.js:9551:11)
    at http://localhost:8000/bower_components/angular/angular.js:9886:13
    at processQueue (http://localhost:8000/bower_components/angular/angular.js:16696:28)
    at http://localhost:8000/bower_components/angular/angular.js:16712:27
    at Scope.$eval (http://localhost:8000/bower_components/angular/angular.js:17994:28)
    at Scope.$digest (http://localhost:8000/bower_components/angular/angular.js:17808:31) <div ng-show="visible" class="row chat-window col-xs-5 col-md-3 {{vm.theme}} ng-isolate-scope" ng-class="{minimized: vm.isHidden}" messages="vm.messages" username="vm.username" input-placeholder-text="You can write here" submit-button-text="Send your message" title="Super Awesome Chat" theme="material" submit-function="vm.sendMessage" visible="vm.visible" expand-on-new="vm.expandOnNew">
```

Any suggestions on how to fix this?

**Comment by wildemat** [comment]
are you including jQuery correctly
